### ISSUE TITLE
Multiple short read libraries

### ISSUE THREAD

**Issue by aabaricalla** [bcgsc/ntedit_sealer_protocol#6]
Hello, I recently discovered this pipeline and I'm already testing it with my data.
Reading the paper and the Help page, I assumed you can pass only one pair-end library.
Can I use another additional library?  e.g.:
reads='lib1_1.fq.gz    lib1_2.fq.gz    lib2_1.fq.gz   lib2_2.fq.gz' 
Or with the deeper library available, it's enough?
Thanks!

**Comment by lcoombe** [comment]
Hi @aabaricalla,

Just checking - is this a different library from the same sample? If so, then yes you could certainly pass the additional reads to the polishing protocol. Whether it would make a big difference to the overall polishing would depend on the coverage of the reads that you're using. 

Hope that helps - thank you for your interest in the ntEdit+Sealer protocol!
Lauren

**Comment by aabaricalla** [comment]
Thanks @lcoombe!
As you said, it's from the same sequencing project. 
I'll try both, with just one or with a couple of libs.
I'll be sharing my results as soon as I get it.
Cheers!
